### ISSUE TITLE
SQL Sever schema migration 76->77 attempts to drop types still in use

### ISSUE THREAD

**Issue by tswelsh** [microsoft/fhir-server#3829]
**Describe the bug**
When running the SQL Server migration scripts, 77.diff.sql attempts to drop a number of "unused" user defined types.  For an old enough starting schema, this tries to drop at least one type that is still in use.  Specifically, there was an error dropping dbo.BulkCompartmentAssignmentTableType_1, which is in use by the procedure dbo.ReindexResource.  This procedure is not dropped first in any migration script.

**FHIR Version?**
Stu3

**Data provider?**
SQL Server

**To Reproduce**
1. Initialise a SQL Server database at a sufficiently low version - I tried starting from the lowest recorded in our version control which was schema version 7.
2. Run the schema migrations (<n>.diff.sql) in order up to at least 77.

**Expected behavior**
All schema migration scripts should complete without error.

**Actual behavior**
On executing 77.diff.sql, SQL Server returns an error:

"Cannot drop type 'dbo.BulkCompartmentAssignmentTableType_1' because it is being referenced by object 'ReindexResource'. There may be other objects that reference this type."

[AB#119628](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/119628)

**Comment by tswelsh** [comment]
Just to add, I pretty much stopped at the first error it ran into - there could be other things referencing types that the script wants to drop.

**Comment by EXPEkesheth** [comment]
@SergeyGaluzo  - is this something you can help look into?

**Comment by SergeyGaluzo** [comment]
@EXPEkesheth I will take a look.

**Comment by SergeyGaluzo** [comment]
Fixed by https://github.com/microsoft/fhir-server/pull/3830

**Comment by tswelsh** [comment]
This isn't fully fixed - the type is also still in use by dbo.BulkReindexResources.

**Comment by SergeyGaluzo** [comment]
Added drop of this stored procedure in this PR https://github.com/microsoft/fhir-server/pull/3833

**Comment by SergeyGaluzo** [comment]
Fixed by https://github.com/microsoft/fhir-server/pull/3833. Please re-test.

**Comment by tswelsh** [comment]
Thanks @SergeyGaluzo, this looks to be fixed now.

**Comment by SergeyGaluzo** [comment]
@tswelsh Thanks for your patience.
